/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
#undef InterfaceAvecC_EMPTY_PAWN
#define InterfaceAvecC_EMPTY_PAWN 0L
#undef InterfaceAvecC_BLACK_PAWN
#define InterfaceAvecC_BLACK_PAWN 1L
#undef InterfaceAvecC_WHITE_PAWN
#define InterfaceAvecC_WHITE_PAWN 2L
/*
 * Class:     InterfaceAvecC
 * Method:    newGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_newGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_endGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    permission
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_InterfaceAvecC_permission
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    setPawn
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_setPawn
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    getPawn
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_getPawn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    hasAWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_hasAWinner
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    saveGame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_saveGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    restoreGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_restoreGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    displayHistoryGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_displayHistoryGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    undo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_undo
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    displayGraphGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_displayGraphGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    displayPlateau
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_displayPlateau
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    displayGroup
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_displayGroup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
