/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
#undef InterfaceAvecC_NO_PAWN
#define InterfaceAvecC_NO_PAWN 0L
#undef InterfaceAvecC_BLACK_PAWN
#define InterfaceAvecC_BLACK_PAWN 1L
#undef InterfaceAvecC_WHITE_PAWN
#define InterfaceAvecC_WHITE_PAWN 2L
/*
 * Class:     InterfaceAvecC
 * Method:    newGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_newGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_endGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    insertPawn
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_insertPawn
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    getPawn
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_getPawn
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    hasAWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_hasAWinner
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    saveGame
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_saveGame
  (JNIEnv *, jclass, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    restoreGame
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_restoreGame
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     InterfaceAvecC
 * Method:    undo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_undo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
