/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    newGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_newGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_endGame
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
