/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InterfaceAvecC */

#ifndef _Included_InterfaceAvecC
#define _Included_InterfaceAvecC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InterfaceAvecC
 * Method:    newGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_newGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    endGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_endGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    permission
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_InterfaceAvecC_permission
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    setPawn
 * Signature: (ZII)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_setPawn
  (JNIEnv *, jclass, jboolean, jint, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    hasAWinner
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_hasAWinner
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    saveGame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_InterfaceAvecC_saveGame
  (JNIEnv *, jclass);

/*
 * Class:     InterfaceAvecC
 * Method:    restoreGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_restoreGame
  (JNIEnv *, jclass, jint);

/*
 * Class:     InterfaceAvecC
 * Method:    undo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InterfaceAvecC_undo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
